# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-Transaction
version:      0.005
version_from: lib/DBIx/Transaction.pm
installdirs:  site
requires:
    DBI:                           1.38
    Test::CPANpm:                  0.008

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
